### PR TITLE
Added support for SLES

### PR DESCRIPTION
**Pull request by thespain**
Please review the commits for adding support to SLES 11 and 12 and let me know if you would like to see any changes.

### CODE REVIEW

**Comment by genebean** [comment]
Please move the checks for the service name to `params.pp` and reference it in both `install.pp` and `service.pp`

**Comment by genebean** [comment]
Please also provide unit tests to cover all changes. This must be done prior to merging.

**Comment by thespain** [comment]
Please see latest commits for the changes requested.

**Comment by genebean** [comment]
@thespain - is this ready or are you still making changes?

**Comment by thespain** [comment]
@genebean In order to complete this branch I had to modify the Gemfile to use v1.8.3 of json and json_pure gems only if the ruby version is less than 2.0 and if the ruby version is greater than 2.0, then the latest gems will be used. Both json and json_pure gems now require ruby > 2.0 as of version 2.0.0. See [change log] (https://github.com/flori/json/blob/master/CHANGES.md) for details.

I also add an option in the vagrant file to resolve an issue by not replace the default insecure ssh key because it ran into an ssh error when attempting to run vagrant up .

**Pull request merged**
